package lk.ci.int_cn_system.UI.SimQuotation;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.Button;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.DateField;
import com.vaadin.ui.Label;
import com.vaadin.ui.OptionGroup;
import com.vaadin.ui.Table;
import com.vaadin.ui.TextField;
import com.vaadin.ui.Upload;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class SimQuotation extends AbsoluteLayout {
	protected ComboBox comboCoverType;
	protected ComboBox comboPolCategory;
	protected ComboBox comboPolUsage;
	protected ComboBox comboProduct;
	protected ComboBox comboPePackageName;
	protected ComboBox comboLocation;
	protected ComboBox comboPeriodOfCover;
	protected DateField dateExpireDate;
	protected OptionGroup optionGroupRegNonReg;
	protected ComboBox comboVehProv;
	protected TextField txtVehLett;
	protected TextField txtVehNos;
	protected TextField txtEngineNo;
	protected TextField txtChassis;
	protected TextField txtSumInsured;
	protected Table tablePerils;
	protected Button buttonClear;
	protected Button buttonSaveQuotation;
	protected Table tablePmtLine;
	protected Button buttonCalTotalPre;
	protected Button buttonSearchByVehicle;
	protected Label labelLoadedQuoNo;
	protected Label lblTotPremium;
	protected Label lblCalNetRate;
	protected Label lblNetPremium;
	protected Label lblDefNetRate;
	protected Button btnCalculatePerils;
	protected ComboBox comboVehType;
	protected TextField txtSeatCount;
	protected TextField txtNIC;
	protected TextField txtMobile;
	protected TextField txtCusInitName;
	protected TextField txtCusLastName;
	protected TextField txtCusAddressNo;
	protected TextField txtCusStreet;
	protected TextField txtCusArea;
	protected ComboBox comboCusCity;
	protected ComboBox comboMakeModel;
	protected Table tableCNReason;
	protected Button buttonSaveCvrNote;
	protected DateField dateStartDate;
	protected DateField dateEndDate;
	protected ComboBox comboYOM;
	protected ComboBox comboDocumentName;
	protected Upload uploadDocument;
	protected Table tableDocumentUpload;
	protected TextField txtQuotationNo;
	protected Button btnQuotationSearch;

	public SimQuotation() {
		Design.read(this);
	}
}
