package lk.ci.int_cn_system.UI.LaonGuarantee;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.DateField;
import com.vaadin.ui.TextField;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class LoanGuarantee extends AbsoluteLayout {
	protected TextField txtApplicantInitName;
	protected TextField txtApplicantLastName;
	protected TextField txtNIC;
	protected TextField txtCusAddressNo;
	protected TextField txtCusStreet;
	protected TextField txtCusArea;
	protected ComboBox comboCusCity;
	protected DateField dateDOB;
	protected TextField txtOccupation;
	protected TextField txtLoanAgreementNo;
	protected TextField txtLoanAgreementNo1;
	protected TextField txtLoanAgreementNo11;
	protected DateField dateDOB1;
	protected TextField txtLoanAgreementNo12;
	protected TextField txtLoanAgreementNo121;
	protected TextField txtLoanAgreementNo1211;
	protected TextField txtLoanAgreementNo1212;
	protected TextField txtLoanAgreementNo12111;
	protected DateField dateDOB2;

	public LoanGuarantee() {
		Design.read(this);
	}
}
